// Simulator orchestration module
// Responsible for translating UI actions into engine signals in a real system.

import type { Event } from "@/types/event";

export function createSimulatedEvent(
  category: Event["category"],
  type: string,
  sequence: number,
): Event {
  return {
    id: `EV-${sequence.toString().padStart(4, "0")}`,
    category,
    type,
    createdAt: new Date().toISOString(),
    meta: "Generated by simulator module",
  };
}

